# Generated by Django 4.1.3 on 2022-12-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_poster',
            new_name='date_posted',
        ),
    ]
